name: php
version: 4.0.0-alpha
schema: 1
scm: github.com/pubnub/php
changelog:
  - version: 4.0.0-alpha
    date:
    changes:
      - type: improvement
        text: Alpha Release
features:
  access:
    - ACCESS-GRANT
    - ACCESS-SECRET-KEY-ALL-ACCESS
  channel-groups:
    - CHANNEL-GROUPS-ADD-CHANNELS
    - CHANNEL-GROUPS-REMOVE-CHANNELS
    - CHANNEL-GROUPS-REMOVE-GROUPS
    - CHANNEL-GROUPS-LIST-CHANNELS-IN-GROUP
  presence:
    - PRESENCE-HERE-NOW
    - PRESENCE-WHERE-NOW
    - PRESENCE-SET-STATE
    - PRESENCE-GET-STATE
  publish:
  - PUBLISH-STORE-FLAG
  - PUBLISH-RAW-JSON
  - PUBLISH-WITH-METADATA
  - PUBLISH-GET
  storage:
  - STORAGE-REVERSE
  - STORAGE-INCLUDE-TIMETOKEN
  - STORAGE-START-END
  - STORAGE-COUNT
  time:
  - TIME-TIME
  subscribe:
  - SUBSCRIBE-CHANNELS
  - SUBSCRIBE-CHANNEL-GROUPS
  - SUBSCRIBE-PRESENCE-CHANNELS
  - SUBSCRIBE-PRESENCE-CHANNELS-GROUPS
  - SUBSCRIBE-WITH-TIMETOKEN
  - SUBSCRIBE-WILDCARD
  - SUBSCRIBE-PUBLISHER-UUID
